#nullable enable annotations
#nullable disable warnings
using StarGen.Tests.Unit.JumpLanes;

namespace StarGen.Tests.Framework;

public static partial class DotNetNativeTestSuite
{
    /// <summary>
    /// Registers all JumpLanes unit tests.
    /// </summary>
    public static void RunJumpLanesTests(DotNetTestRunner runner)
    {
        runner.RunNativeTest(
            "TestJumpLaneSystem::test_init_defaults",
            TestJumpLaneSystem.TestInitDefaults);
        runner.RunNativeTest(
            "TestJumpLaneSystem::test_init_with_values",
            TestJumpLaneSystem.TestInitWithValues);
        runner.RunNativeTest(
            "TestJumpLaneSystem::test_is_populated_true",
            TestJumpLaneSystem.TestIsPopulatedTrue);
        runner.RunNativeTest(
            "TestJumpLaneSystem::test_is_populated_false",
            TestJumpLaneSystem.TestIsPopulatedFalse);
        runner.RunNativeTest(
            "TestJumpLaneSystem::test_effective_population_without_false",
            TestJumpLaneSystem.TestEffectivePopulationWithoutFalse);
        runner.RunNativeTest(
            "TestJumpLaneSystem::test_effective_population_with_false",
            TestJumpLaneSystem.TestEffectivePopulationWithFalse);
        runner.RunNativeTest(
            "TestJumpLaneSystem::test_distance_to",
            TestJumpLaneSystem.TestDistanceTo);
        runner.RunNativeTest(
            "TestJumpLaneSystem::test_distance_to_3d",
            TestJumpLaneSystem.TestDistanceTo3d);
        runner.RunNativeTest(
            "TestJumpLaneSystem::test_make_bridge",
            TestJumpLaneSystem.TestMakeBridge);
        runner.RunNativeTest(
            "TestJumpLaneSystem::test_make_bridge_clamps_negative",
            TestJumpLaneSystem.TestMakeBridgeClampsNegative);
        runner.RunNativeTest(
            "TestJumpLaneSystem::test_serialization_round_trip",
            TestJumpLaneSystem.TestSerializationRoundTrip);

        runner.RunNativeTest(
            "TestJumpLaneConnection::test_init_defaults",
            TestJumpLaneConnection.TestInitDefaults);
        runner.RunNativeTest(
            "TestJumpLaneConnection::test_init_with_values",
            TestJumpLaneConnection.TestInitWithValues);
        runner.RunNativeTest(
            "TestJumpLaneConnection::test_serialization_round_trip",
            TestJumpLaneConnection.TestSerializationRoundTrip);

        runner.RunNativeTest(
            "TestJumpLaneRegion::test_init_defaults",
            TestJumpLaneRegion.TestInitDefaults);
        runner.RunNativeTest(
            "TestJumpLaneRegion::test_init_with_values",
            TestJumpLaneRegion.TestInitWithValues);
        runner.RunNativeTest(
            "TestJumpLaneRegion::test_add_system",
            TestJumpLaneRegion.TestAddSystem);
        runner.RunNativeTest(
            "TestJumpLaneRegion::test_remove_system",
            TestJumpLaneRegion.TestRemoveSystem);
        runner.RunNativeTest(
            "TestJumpLaneRegion::test_remove_system_not_found",
            TestJumpLaneRegion.TestRemoveSystemNotFound);
        runner.RunNativeTest(
            "TestJumpLaneRegion::test_get_system",
            TestJumpLaneRegion.TestGetSystem);
        runner.RunNativeTest(
            "TestJumpLaneRegion::test_get_system_not_found",
            TestJumpLaneRegion.TestGetSystemNotFound);
        runner.RunNativeTest(
            "TestJumpLaneRegion::test_get_populated_systems",
            TestJumpLaneRegion.TestGetPopulatedSystems);
        runner.RunNativeTest(
            "TestJumpLaneRegion::test_get_unpopulated_systems",
            TestJumpLaneRegion.TestGetUnpopulatedSystems);
        runner.RunNativeTest(
            "TestJumpLaneRegion::test_get_systems_sorted_by_population",
            TestJumpLaneRegion.TestGetSystemsSortedByPopulation);
        runner.RunNativeTest(
            "TestJumpLaneRegion::test_get_populated_count",
            TestJumpLaneRegion.TestGetPopulatedCount);
        runner.RunNativeTest(
            "TestJumpLaneRegion::test_clear",
            TestJumpLaneRegion.TestClear);
        runner.RunNativeTest(
            "TestJumpLaneRegion::test_serialization_round_trip",
            TestJumpLaneRegion.TestSerializationRoundTrip);

        runner.RunNativeTest(
            "TestJumpLaneResult::test_add_connection_and_total",
            TestJumpLaneResult.TestAddConnectionAndTotal);
        runner.RunNativeTest(
            "TestJumpLaneResult::test_add_orphan_and_total",
            TestJumpLaneResult.TestAddOrphanAndTotal);
        runner.RunNativeTest(
            "TestJumpLaneResult::test_is_orphan",
            TestJumpLaneResult.TestIsOrphan);
        runner.RunNativeTest(
            "TestJumpLaneResult::test_get_connection_counts",
            TestJumpLaneResult.TestGetConnectionCounts);
        runner.RunNativeTest(
            "TestJumpLaneResult::test_get_connections_for_system",
            TestJumpLaneResult.TestGetConnectionsForSystem);
        runner.RunNativeTest(
            "TestJumpLaneResult::test_register_system",
            TestJumpLaneResult.TestRegisterSystem);
        runner.RunNativeTest(
            "TestJumpLaneResult::test_serialization_round_trip",
            TestJumpLaneResult.TestSerializationRoundTrip);

        runner.RunNativeTest(
            "TestJumpLaneCalculator::test_empty_region_returns_empty_result",
            TestJumpLaneCalculator.TestEmptyRegionReturnsEmptyResult);
        runner.RunNativeTest(
            "TestJumpLaneCalculator::test_single_system_is_orphan",
            TestJumpLaneCalculator.TestSingleSystemIsOrphan);
        runner.RunNativeTest(
            "TestJumpLaneCalculator::test_two_systems_within_3pc_green_connection",
            TestJumpLaneCalculator.TestTwoSystemsWithin3pcGreenConnection);
        runner.RunNativeTest(
            "TestJumpLaneCalculator::test_two_systems_within_5pc_green_connection",
            TestJumpLaneCalculator.TestTwoSystemsWithin5pcGreenConnection);
        runner.RunNativeTest(
            "TestJumpLaneCalculator::test_two_systems_at_7pc_no_bridge_orange_connection",
            TestJumpLaneCalculator.TestTwoSystemsAt7pcNoBridgeOrangeConnection);
        runner.RunNativeTest(
            "TestJumpLaneCalculator::test_two_systems_at_9pc_no_bridge_no_connection",
            TestJumpLaneCalculator.TestTwoSystemsAt9pcNoBridgeNoConnection);
        runner.RunNativeTest(
            "TestJumpLaneCalculator::test_two_systems_beyond_9pc_no_connection",
            TestJumpLaneCalculator.TestTwoSystemsBeyond9pcNoConnection);
        runner.RunNativeTest(
            "TestJumpLaneCalculator::test_bridge_creates_yellow_connections",
            TestJumpLaneCalculator.TestBridgeCreatesYellowConnections);
        runner.RunNativeTest(
            "TestJumpLaneCalculator::test_bridge_gets_false_population",
            TestJumpLaneCalculator.TestBridgeGetsFalsePopulation);
        runner.RunNativeTest(
            "TestJumpLaneCalculator::test_bridge_not_used_as_source",
            TestJumpLaneCalculator.TestBridgeNotUsedAsSource);
        runner.RunNativeTest(
            "TestJumpLaneCalculator::test_bridge_must_be_within_5pc_of_both",
            TestJumpLaneCalculator.TestBridgeMustBeWithin5pcOfBoth);
        runner.RunNativeTest(
            "TestJumpLaneCalculator::test_connects_to_highest_populated_within_threshold",
            TestJumpLaneCalculator.TestConnectsToHighestPopulatedWithinThreshold);
        runner.RunNativeTest(
            "TestJumpLaneCalculator::test_processes_lowest_population_first",
            TestJumpLaneCalculator.TestProcessesLowestPopulationFirst);
        runner.RunNativeTest(
            "TestJumpLaneCalculator::test_multiple_orphans",
            TestJumpLaneCalculator.TestMultipleOrphans);
        runner.RunNativeTest(
            "TestJumpLaneCalculator::test_chain_of_connections",
            TestJumpLaneCalculator.TestChainOfConnections);
        runner.RunNativeTest(
            "TestJumpLaneCalculator::test_mixed_connection_types",
            TestJumpLaneCalculator.TestMixedConnectionTypes);
        runner.RunNativeTest(
            "TestJumpLaneCalculator::test_system_can_receive_multiple_inbound_connections",
            TestJumpLaneCalculator.TestSystemCanReceiveMultipleInboundConnections);
        runner.RunNativeTest(
            "TestJumpLaneCalculator::test_highest_pop_system_is_not_orphan_when_receiving_connections",
            TestJumpLaneCalculator.TestHighestPopSystemIsNotOrphanWhenReceivingConnections);
        runner.RunNativeTest(
            "TestJumpLaneCalculator::test_unpopulated_systems_ignored_as_destinations",
            TestJumpLaneCalculator.TestUnpopulatedSystemsIgnoredAsDestinations);
        runner.RunNativeTest(
            "TestJumpLaneCalculator::test_3d_distances",
            TestJumpLaneCalculator.Test3dDistances);
        runner.RunNativeTest(
            "TestJumpLaneCalculator::test_equal_population_still_connects",
            TestJumpLaneCalculator.TestEqualPopulationStillConnects);
        runner.RunNativeTest(
            "TestJumpLaneCalculator::test_exactly_at_threshold_boundaries",
            TestJumpLaneCalculator.TestExactlyAtThresholdBoundaries);
        runner.RunNativeTest(
            "TestJumpLaneCalculator::test_just_beyond_threshold",
            TestJumpLaneCalculator.TestJustBeyondThreshold);

        runner.RunNativeTest(
            "TestJumpLaneClusterConnector::test_single_system_is_one_cluster",
            TestJumpLaneClusterConnector.TestSingleSystemIsOneCluster);
        runner.RunNativeTest(
            "TestJumpLaneClusterConnector::test_two_disconnected_systems_within_range_get_connected",
            TestJumpLaneClusterConnector.TestTwoDisconnectedSystemsWithinRangeGetConnected);
        runner.RunNativeTest(
            "TestJumpLaneClusterConnector::test_two_disconnected_systems_beyond_range_stay_disconnected",
            TestJumpLaneClusterConnector.TestTwoDisconnectedSystemsBeyondRangeStayDisconnected);
        runner.RunNativeTest(
            "TestJumpLaneClusterConnector::test_three_clusters_connected_iteratively",
            TestJumpLaneClusterConnector.TestThreeClustersConnectedIteratively);
        runner.RunNativeTest(
            "TestJumpLaneClusterConnector::test_already_connected_systems_form_single_cluster",
            TestJumpLaneClusterConnector.TestAlreadyConnectedSystemsFormSingleCluster);
        runner.RunNativeTest(
            "TestJumpLaneClusterConnector::test_cluster_connection_uses_green_within_5pc",
            TestJumpLaneClusterConnector.TestClusterConnectionUsesGreenWithin5pc);
        runner.RunNativeTest(
            "TestJumpLaneClusterConnector::test_cluster_connection_uses_orange_at_7pc_no_bridge",
            TestJumpLaneClusterConnector.TestClusterConnectionUsesOrangeAt7pcNoBridge);
        runner.RunNativeTest(
            "TestJumpLaneClusterConnector::test_cluster_connection_uses_bridge_when_available",
            TestJumpLaneClusterConnector.TestClusterConnectionUsesBridgeWhenAvailable);
        runner.RunNativeTest(
            "TestJumpLaneClusterConnector::test_connects_closest_clusters_first",
            TestJumpLaneClusterConnector.TestConnectsClosestClustersFirst);
        runner.RunNativeTest(
            "TestJumpLaneClusterConnector::test_orphan_removed_when_connected",
            TestJumpLaneClusterConnector.TestOrphanRemovedWhenConnected);
        runner.RunNativeTest(
            "TestJumpLaneClusterConnector::test_unpopulated_systems_not_in_clusters",
            TestJumpLaneClusterConnector.TestUnpopulatedSystemsNotInClusters);
        runner.RunNativeTest(
            "TestJumpLaneClusterConnector::test_extended_direct_red_when_clusters_within_10pc",
            TestJumpLaneClusterConnector.TestExtendedDirectRedWhenClustersWithin10pc);
        runner.RunNativeTest(
            "TestJumpLaneClusterConnector::test_extended_multi_hop_red_when_stepping_stones_within_10pc",
            TestJumpLaneClusterConnector.TestExtendedMultiHopRedWhenSteppingStonesWithin10pc);
    }
}
