## Contains the results of a jump lane calculation.
## Holds all connections and orphan system IDs.
class_name JumpLaneResult
extends RefCounted


## All connections generated by the calculation.
var connections: Array[JumpLaneConnection] = []

## IDs of systems with no connections (orphans).
var orphan_ids: Array[String] = []

## Systems that were processed (for reference).
var systems: Dictionary = {} # id -> JumpLaneSystem


## Adds a connection to the result.
## @param connection: The connection to add.
func add_connection(connection: JumpLaneConnection) -> void:
	connections.append(connection)


## Adds an orphan system ID.
## @param system_id: The orphan system's ID.
func add_orphan(system_id: String) -> void:
	orphan_ids.append(system_id)


## Registers a system in the result.
## @param system: The system to register.
func register_system(system: JumpLaneSystem) -> void:
	systems[system.id] = system


## Returns the count of each connection type.
## @return: Dictionary with type counts.
func get_connection_counts() -> Dictionary:
	var counts: Dictionary = {
		JumpLaneConnection.ConnectionType.GREEN: 0,
		JumpLaneConnection.ConnectionType.YELLOW: 0,
		JumpLaneConnection.ConnectionType.ORANGE: 0
	}
	for conn in connections:
		counts[conn.connection_type] += 1
	return counts


## Returns all connections involving a specific system.
## @param system_id: The system ID to search for.
## @return: Array of connections involving this system.
func get_connections_for_system(system_id: String) -> Array[JumpLaneConnection]:
	var result: Array[JumpLaneConnection] = []
	for conn in connections:
		if conn.source_id == system_id or conn.destination_id == system_id:
			result.append(conn)
	return result


## Returns whether a system is an orphan.
## @param system_id: The system ID to check.
## @return: True if the system is an orphan.
func is_orphan(system_id: String) -> bool:
	return system_id in orphan_ids


## Returns the total number of connections.
## @return: Connection count.
func get_total_connections() -> int:
	return connections.size()


## Returns the total number of orphans.
## @return: Orphan count.
func get_total_orphans() -> int:
	return orphan_ids.size()


## Creates a dictionary representation for serialization.
## @return: Dictionary with result data.
func to_dict() -> Dictionary:
	var conn_array: Array[Dictionary] = []
	for conn in connections:
		conn_array.append(conn.to_dict())

	var system_array: Array[Dictionary] = []
	for system in systems.values():
		system_array.append((system as JumpLaneSystem).to_dict())

	return {
		"connections": conn_array,
		"orphan_ids": orphan_ids,
		"systems": system_array
	}


## Creates a JumpLaneResult from a dictionary.
## @param data: Dictionary with result data.
## @return: New JumpLaneResult instance.
static func from_dict(data: Dictionary) -> RefCounted:
	var result: JumpLaneResult = JumpLaneResult.new()

	var connections_data: Array = data.get("connections", [])
	for conn_data in connections_data:
		result.connections.append(JumpLaneConnection.from_dict(conn_data as Dictionary))

	var orphans_data: Array = data.get("orphan_ids", [])
	for orphan_id in orphans_data:
		result.orphan_ids.append(orphan_id as String)

	var systems_data: Array = data.get("systems", [])
	for system_data in systems_data:
		var system: JumpLaneSystem = JumpLaneSystem.from_dict(system_data as Dictionary)
		result.systems[system.id] = system

	return result
