using Godot;
using StarGen.App.Viewer;
using StarGen.Domain.Generation;

namespace StarGen.App;

/// <summary>
/// Pre-launch studio for standalone object generation.
/// </summary>
public partial class ObjectGenerationScreen : Control
{
    [Signal]
    public delegate void start_object_generationEventHandler(ObjectGenerationRequest request);

    [Signal]
    public delegate void load_object_requestedEventHandler();

    [Signal]
    public delegate void back_requestedEventHandler();

    private VBoxContainer? _parameterVBox;
    private Label? _versionLabel;
    private Label? _summaryLabel;
    private Label? _assumptionsLabel;
    private VBoxContainer? _issuesContainer;
    private Button? _startButton;
    private Button? _loadButton;
    private Button? _backButton;
    private OptionButton? _typeOption;
    private OptionButton? _presetOption;
    private SpinBox? _seedInput;
    private OptionButton? _rulesetModeOption;
    private CheckBox? _showTravellerReadoutsCheck;
    private SpinBox? _lifePermissivenessInput;
    private SpinBox? _populationPermissivenessInput;

    /// <summary>
    /// Builds the screen and initializes controls.
    /// </summary>
    public override void _Ready()
    {
        CacheNodeReferences();
        BuildParameterUi();
        ConnectSignals();
        ApplyVersionLabel();
        ApplyDefaults();
        RefreshSummary();
    }

    /// <summary>
    /// Applies a seed generated by the parent app.
    /// </summary>
    public void SetInitialSeed(int seedValue)
    {
        if (_seedInput != null)
        {
            _seedInput.Value = seedValue;
        }

        RefreshSummary();
    }

    /// <summary>
    /// Returns the currently selected launch request.
    /// </summary>
    public ObjectGenerationRequest GetCurrentRequest()
    {
        ObjectGenerationRequest request = new ObjectGenerationRequest();
        if (_typeOption != null)
        {
            request.ObjectType = (ObjectViewer.ObjectType)_typeOption.GetSelectedId();
        }

        if (_presetOption != null)
        {
            request.PresetId = _presetOption.GetSelectedId();
        }

        if (_seedInput != null)
        {
            request.SeedValue = (int)_seedInput.Value;
        }

        request.UseCaseSettings = BuildUseCaseSettingsFromControls();
        return request;
    }

    private void CacheNodeReferences()
    {
        const string Root = "MarginContainer/MainPanel/MarginContainer/VBox";
        _versionLabel = GetNodeOrNull<Label>($"{Root}/HeaderRow/VersionLabel");
        _parameterVBox = GetNodeOrNull<VBoxContainer>($"{Root}/StudioRow/SettingsPanel/MarginContainer/SettingsVBox/ScrollContainer/ParameterVBox");
        _summaryLabel = GetNodeOrNull<Label>($"{Root}/StudioRow/SummaryPanel/MarginContainer/SummaryVBox/SummaryLabel");
        _assumptionsLabel = GetNodeOrNull<Label>($"{Root}/StudioRow/SummaryPanel/MarginContainer/SummaryVBox/AssumptionsLabel");
        _issuesContainer = GetNodeOrNull<VBoxContainer>($"{Root}/StudioRow/SummaryPanel/MarginContainer/SummaryVBox/IssuesContainer");
        _startButton = GetNodeOrNull<Button>($"{Root}/StudioRow/SummaryPanel/MarginContainer/SummaryVBox/Buttons/StartButton");
        _loadButton = GetNodeOrNull<Button>($"{Root}/StudioRow/SummaryPanel/MarginContainer/SummaryVBox/Buttons/LoadButton");
        _backButton = GetNodeOrNull<Button>($"{Root}/HeaderRow/BackButton");
    }

    private void BuildParameterUi()
    {
        if (_parameterVBox == null || _typeOption != null)
        {
            return;
        }

        _typeOption = AddOptionRow("Type");
        _typeOption.AddItem("Star", (int)ObjectViewer.ObjectType.Star);
        _typeOption.AddItem("Planet", (int)ObjectViewer.ObjectType.Planet);
        _typeOption.AddItem("Moon", (int)ObjectViewer.ObjectType.Moon);
        _typeOption.AddItem("Asteroid", (int)ObjectViewer.ObjectType.Asteroid);

        _presetOption = AddOptionRow("Preset");
        _seedInput = AddSpinRow("Seed", 1.0, 999999.0, 1.0);
        _rulesetModeOption = AddOptionRow("Ruleset");
        _rulesetModeOption.AddItem("Default", (int)GenerationUseCaseSettings.RulesetModeType.Default);
        _rulesetModeOption.AddItem("Traveller", (int)GenerationUseCaseSettings.RulesetModeType.Traveller);
        _showTravellerReadoutsCheck = AddCheckRow("Show Traveller / UWP Readouts");
        _lifePermissivenessInput = AddSpinRow("Life Bias", 0.0, 1.0, 0.05);
        _populationPermissivenessInput = AddSpinRow("Pop. Bias", 0.0, 1.0, 0.05);

        RebuildPresetOptions();
    }

    private SpinBox AddSpinRow(string labelText, double minValue, double maxValue, double step)
    {
        HBoxContainer row = CreateRow(labelText);
        SpinBox spinBox = new SpinBox();
        spinBox.MinValue = minValue;
        spinBox.MaxValue = maxValue;
        spinBox.Step = step;
        spinBox.Rounded = step >= 1.0;
        spinBox.SizeFlagsHorizontal = Control.SizeFlags.ExpandFill;
        row.AddChild(spinBox);
        return spinBox;
    }

    private CheckBox AddCheckRow(string labelText)
    {
        CheckBox checkBox = new CheckBox();
        checkBox.Text = labelText;
        _parameterVBox!.AddChild(checkBox);
        return checkBox;
    }

    private OptionButton AddOptionRow(string labelText)
    {
        HBoxContainer row = CreateRow(labelText);
        OptionButton optionButton = new OptionButton();
        optionButton.SizeFlagsHorizontal = Control.SizeFlags.ExpandFill;
        row.AddChild(optionButton);
        return optionButton;
    }

    private HBoxContainer CreateRow(string labelText)
    {
        HBoxContainer row = new HBoxContainer();
        row.AddThemeConstantOverride("separation", 10);
        Label label = new Label();
        label.Text = labelText;
        label.CustomMinimumSize = new Vector2(110.0f, 0.0f);
        row.AddChild(label);
        _parameterVBox!.AddChild(row);
        return row;
    }

    private void ConnectSignals()
    {
        if (_startButton != null)
        {
            _startButton.Pressed += OnStartPressed;
        }

        if (_loadButton != null)
        {
            _loadButton.Pressed += () => EmitSignal(SignalName.load_object_requested);
        }

        if (_backButton != null)
        {
            _backButton.Pressed += () => EmitSignal(SignalName.back_requested);
        }

        if (_typeOption != null)
        {
            _typeOption.ItemSelected += _ => OnTypeChanged();
        }

        if (_presetOption != null)
        {
            _presetOption.ItemSelected += _ => RefreshSummary();
        }

        if (_seedInput != null)
        {
            _seedInput.ValueChanged += _ => RefreshSummary();
        }

        if (_rulesetModeOption != null)
        {
            _rulesetModeOption.ItemSelected += OnRulesetModeSelected;
        }

        if (_showTravellerReadoutsCheck != null)
        {
            _showTravellerReadoutsCheck.Toggled += _ => RefreshSummary();
        }

        if (_lifePermissivenessInput != null)
        {
            _lifePermissivenessInput.ValueChanged += _ => RefreshSummary();
        }

        if (_populationPermissivenessInput != null)
        {
            _populationPermissivenessInput.ValueChanged += _ => RefreshSummary();
        }
    }

    private void ApplyVersionLabel()
    {
        if (_versionLabel != null)
        {
            string version = ProjectSettings.GetSetting("application/config/version", "0.4.1.0").AsString();
            _versionLabel.Text = $"Version {version}";
        }
    }

    private void ApplyDefaults()
    {
        if (_typeOption != null)
        {
            _typeOption.Select((int)ObjectViewer.ObjectType.Planet);
        }

        if (_seedInput != null)
        {
            _seedInput.Value = 12345.0;
        }

        if (_rulesetModeOption != null)
        {
            _rulesetModeOption.Select((int)GenerationUseCaseSettings.RulesetModeType.Default);
        }

        if (_showTravellerReadoutsCheck != null)
        {
            _showTravellerReadoutsCheck.ButtonPressed = false;
        }

        if (_lifePermissivenessInput != null)
        {
            _lifePermissivenessInput.Value = 0.5;
        }

        if (_populationPermissivenessInput != null)
        {
            _populationPermissivenessInput.Value = 0.5;
        }

        RebuildPresetOptions();
    }

    private void OnStartPressed()
    {
        EmitSignal(SignalName.start_object_generation, GetCurrentRequest());
    }

    private void OnTypeChanged()
    {
        RebuildPresetOptions();
        RefreshSummary();
    }

    private void OnRulesetModeSelected(long selectedId)
    {
        if (selectedId == (long)GenerationUseCaseSettings.RulesetModeType.Traveller)
        {
            if (_showTravellerReadoutsCheck != null)
            {
                _showTravellerReadoutsCheck.ButtonPressed = true;
            }
        }

        RefreshSummary();
    }

    private void RebuildPresetOptions()
    {
        if (_presetOption == null)
        {
            return;
        }

        _presetOption.Clear();
        ObjectViewer.ObjectType objectType = GetSelectedObjectType();
        if (objectType == ObjectViewer.ObjectType.Star)
        {
            _presetOption.AddItem("Random", 0);
            _presetOption.AddItem("Sun-like", 1);
            _presetOption.AddItem("Red Dwarf", 2);
            _presetOption.AddItem("Hot Blue", 3);
        }
        else if (objectType == ObjectViewer.ObjectType.Planet)
        {
            _presetOption.AddItem("Random", 0);
            _presetOption.AddItem("Earth-like", 1);
            _presetOption.AddItem("Hot Jupiter", 2);
            _presetOption.AddItem("Cold Giant", 3);
            _presetOption.AddItem("Mars-like", 4);
            _presetOption.AddItem("Dwarf Planet", 5);
            _presetOption.AddItem("Ice Giant", 6);
        }
        else if (objectType == ObjectViewer.ObjectType.Moon)
        {
            _presetOption.AddItem("Random", 0);
            _presetOption.AddItem("Luna-like", 1);
            _presetOption.AddItem("Europa-like", 2);
            _presetOption.AddItem("Titan-like", 3);
            _presetOption.AddItem("Captured", 4);
        }
        else
        {
            _presetOption.AddItem("Random", 0);
        }

        _presetOption.Select(0);
    }

    private void RefreshSummary()
    {
        ObjectGenerationRequest request = GetCurrentRequest();
        if (_summaryLabel != null)
        {
            _summaryLabel.Text =
                $"Seed {request.SeedValue}\n" +
                $"Type {request.ObjectType}\n" +
                $"Preset {GetSelectedPresetLabel()}\n" +
                $"Ruleset {request.UseCaseSettings.RulesetMode}\n" +
                $"Traveller Readouts {(request.UseCaseSettings.ShowTravellerReadouts ? "On" : "Off")}";
        }

        if (_assumptionsLabel != null)
        {
            _assumptionsLabel.Text = "Preset assumptions and use-case settings will be persisted into the generated body so downstream inspection and save/load flows stay aligned.";
        }

        RefreshIssuesUi();
    }

    private void RefreshIssuesUi()
    {
        if (_issuesContainer == null)
        {
            return;
        }

        foreach (Node child in _issuesContainer.GetChildren())
        {
            child.QueueFree();
        }

        Label noteLabel = new Label();
        noteLabel.AutowrapMode = TextServer.AutowrapMode.Word;
        noteLabel.Modulate = new Color(0.85f, 0.7f, 0.3f, 1.0f);
        noteLabel.Text = GetPresetAssumptionText(GetSelectedObjectType(), _presetOption?.GetSelectedId() ?? 0);
        _issuesContainer.AddChild(noteLabel);
    }

    private ObjectViewer.ObjectType GetSelectedObjectType()
    {
        if (_typeOption == null)
        {
            return ObjectViewer.ObjectType.Planet;
        }

        return (ObjectViewer.ObjectType)_typeOption.GetSelectedId();
    }

    private string GetSelectedPresetLabel()
    {
        if (_presetOption == null || _presetOption.ItemCount == 0)
        {
            return "Random";
        }

        int selectedIndex = _presetOption.GetSelected();
        if (selectedIndex < 0 || selectedIndex >= _presetOption.ItemCount)
        {
            return "Random";
        }

        return _presetOption.GetItemText(selectedIndex);
    }

    private GenerationUseCaseSettings BuildUseCaseSettingsFromControls()
    {
        GenerationUseCaseSettings settings = GenerationUseCaseSettings.CreateDefault();
        if (_rulesetModeOption != null)
        {
            settings.RulesetMode = (GenerationUseCaseSettings.RulesetModeType)_rulesetModeOption.GetSelectedId();
        }

        if (_showTravellerReadoutsCheck != null)
        {
            settings.ShowTravellerReadouts = _showTravellerReadoutsCheck.ButtonPressed;
        }

        if (_lifePermissivenessInput != null)
        {
            settings.LifePermissiveness = _lifePermissivenessInput.Value;
        }

        if (_populationPermissivenessInput != null)
        {
            settings.PopulationPermissiveness = _populationPermissivenessInput.Value;
        }

        return settings;
    }

    private static string GetPresetAssumptionText(ObjectViewer.ObjectType objectType, int presetId)
    {
        if (objectType == ObjectViewer.ObjectType.Star)
        {
            if (presetId == 1)
            {
                return "Sun-like targets a G-class star with near-solar metallicity while the rest stays deterministic.";
            }

            if (presetId == 2)
            {
                return "Red Dwarf biases toward an M-class star and leaves age and metallicity seed-driven.";
            }

            if (presetId == 3)
            {
                return "Hot Blue biases toward a luminous B-class star and remains intentionally rare.";
            }

            return "Random leaves the stellar parameter set open for a full seed-driven roll.";
        }

        if (objectType == ObjectViewer.ObjectType.Planet)
        {
            if (presetId == 1)
            {
                return "Earth-like targets a temperate terrestrial world with atmosphere present and rings disabled.";
            }

            if (presetId == 2)
            {
                return "Hot Jupiter targets a close-in gas giant while chemistry and visuals stay seed-driven.";
            }

            if (presetId == 3)
            {
                return "Cold Giant targets an outer gas giant and leaves ring complexity open.";
            }

            if (presetId == 4)
            {
                return "Mars-like biases toward a smaller cold terrestrial world with a thin-atmosphere target.";
            }

            if (presetId == 5)
            {
                return "Dwarf Planet locks a dwarf-size target with no atmosphere or rings.";
            }

            if (presetId == 6)
            {
                return "Ice Giant targets a Neptune-class world in the cold zone and prefers trace rings.";
            }

            return "Random leaves size, orbit zone, atmosphere, and ring targets open.";
        }

        if (objectType == ObjectViewer.ObjectType.Moon)
        {
            if (presetId == 1)
            {
                return "Luna-like targets a dry sub-terrestrial moon with no atmosphere or subsurface ocean.";
            }

            if (presetId == 2)
            {
                return "Europa-like targets a cold moon with a subsurface ocean and no atmosphere.";
            }

            if (presetId == 3)
            {
                return "Titan-like targets a moon with atmosphere and subsurface-ocean preferences.";
            }

            if (presetId == 4)
            {
                return "Captured biases toward a smaller irregular moon marked as captured.";
            }

            return "Random leaves capture state, atmosphere, and ocean targets open.";
        }

        return "Random asteroid generation leaves composition and size open for the seed to resolve.";
    }
}
