using Godot;
using StarGen.App.Components;
using StarGen.App.Shared;
using StarGen.App.Viewer;
using StarGen.Domain.Generation;

namespace StarGen.App;

/// <summary>
/// Pre-launch studio for standalone object generation.
/// </summary>
public partial class ObjectGenerationScreen : Control
{
    [Signal]
    public delegate void start_object_generationEventHandler(ObjectGenerationRequest request);

    [Signal]
    public delegate void back_requestedEventHandler();

    private VBoxContainer? _parameterVBox;
    private BoxContainer? _studioRow;
    private Control? _settingsPanel;
    private Control? _rulesPanel;
    private Control? _summaryPanel;
    private Label? _versionLabel;
    private Label? _summaryLabel;
    private Label? _assumptionsLabel;
    private VBoxContainer? _issuesContainer;
    private Button? _startButton;
    private Button? _loadButton;
    private Button? _backButton;
    private HBoxContainer? _seedRow;
    private OptionButton? _typeOption;
    private OptionButton? _presetOption;
    private SpinBox? _seedInput;
    private OptionButton? _rulesetModeOption;
    private CheckBox? _showTravellerReadoutsCheck;
    private bool _showSeedControls;

    /// <summary>
    /// Builds the screen and initializes controls.
    /// </summary>
    public override void _Ready()
    {
        CacheNodeReferences();
        ApplyLayoutPolish();
        BuildParameterUi();
        ConnectSignals();
        ApplyVersionLabel();
        ApplyDefaults();
        ApplySeedVisibilityPreference(rerollHiddenSeed: true);
        RefreshSummary();
        ApplyResponsiveLayout();
        Resized += ApplyResponsiveLayout;
    }

    /// <summary>
    /// Applies a seed generated by the parent app.
    /// </summary>
    public void SetInitialSeed(int seedValue)
    {
        if (_seedInput != null)
        {
            _seedInput.Value = seedValue;
        }

        RefreshSummary();
    }

    /// <summary>
    /// Applies the global studio seed-visibility preference and optionally rerolls hidden seeds.
    /// </summary>
    public void ApplySeedVisibilityPreference(bool rerollHiddenSeed)
    {
        StarGen.Services.Persistence.StudioUiPreferencesService.StudioUiPreferences preferences =
            StarGen.Services.Persistence.StudioUiPreferencesService.LoadOrDefault();
        _showSeedControls = preferences.ShowSeedControls;

        if (_seedRow != null)
        {
            _seedRow.Visible = _showSeedControls;
        }

        if (rerollHiddenSeed && !_showSeedControls && _seedInput != null)
        {
            _seedInput.Value = GenerateHiddenSeed();
        }

        RefreshSummary();
    }

    /// <summary>
    /// Returns the currently selected launch request.
    /// </summary>
    public ObjectGenerationRequest GetCurrentRequest()
    {
        return BuildEnhancedRequest();
    }

    private void CacheNodeReferences()
    {
        const string Root = "MarginContainer/ScrollContainer/Layout/MainPanel/MarginContainer/VBox";
        const string HeroRoot = "MarginContainer/ScrollContainer/Layout/HeroPanel/MarginContainer/HeroVBox";
        _studioRow = GetNodeOrNull<BoxContainer>($"{Root}/StudioRow");
        _settingsPanel = GetNodeOrNull<Control>($"{Root}/StudioRow/SettingsPanel");
        _rulesPanel = GetNodeOrNull<Control>($"{Root}/StudioRow/RulesPanel");
        _summaryPanel = GetNodeOrNull<Control>($"{Root}/StudioRow/SummaryPanel");
        _versionLabel = GetNodeOrNull<Label>($"{HeroRoot}/HeaderRow/VersionLabel");
        _parameterVBox = GetNodeOrNull<VBoxContainer>($"{Root}/StudioRow/SettingsPanel/MarginContainer/SettingsVBox/ScrollContainer/ParameterVBox");
        _summaryLabel = GetNodeOrNull<Label>($"{Root}/StudioRow/SummaryPanel/MarginContainer/SummaryVBox/SummaryScroll/SummaryContent/SummaryLabel");
        _assumptionsLabel = GetNodeOrNull<Label>($"{Root}/StudioRow/SummaryPanel/MarginContainer/SummaryVBox/SummaryScroll/SummaryContent/AssumptionsLabel");
        _issuesContainer = GetNodeOrNull<VBoxContainer>($"{Root}/StudioRow/SummaryPanel/MarginContainer/SummaryVBox/SummaryScroll/SummaryContent/IssuesContainer");
        _startButton = GetNodeOrNull<Button>($"{Root}/StudioRow/SummaryPanel/MarginContainer/SummaryVBox/Buttons/StartButton");
        _loadButton = GetNodeOrNull<Button>($"{Root}/StudioRow/SummaryPanel/MarginContainer/SummaryVBox/Buttons/LoadButton");
        _backButton = GetNodeOrNull<Button>($"{HeroRoot}/HeaderRow/BackButton");
    }

    private void BuildParameterUi()
    {
        BuildEnhancedParameterUi();
    }

    private void ApplyResponsiveLayout()
    {
        StudioScreenLayoutHelper.ApplyResponsiveStudioLayout(this, _studioRow, _settingsPanel, _rulesPanel, _summaryPanel);
    }

    private void ConnectSignals()
    {
        ConnectEnhancedSignals();
    }

    private void ApplyVersionLabel()
    {
        if (_versionLabel != null)
        {
			string version = UserFacingVersionHelper.GetDisplayVersion();
            _versionLabel.Text = $"Version {version}";
        }
    }

    private void ApplyDefaults()
    {
        ApplyEnhancedDefaults();
    }

    private void OnStartPressed()
    {
        if (!_showSeedControls && _seedInput != null)
        {
            _seedInput.Value = GenerateHiddenSeed();
        }

        EmitSignal(SignalName.start_object_generation, GetCurrentRequest());
    }

    private void OnTypeChanged()
    {
        OnEnhancedTypeChanged();
    }

    private void OnRulesetModeSelected(long selectedId)
    {
        OnEnhancedRulesetModeSelected(selectedId);
    }

    private void RebuildPresetOptions()
    {
        RebuildEnhancedPresetOptions();
    }

    private void RefreshSummary()
    {
        RefreshEnhancedSummary();
    }

    private void ApplyLayoutPolish()
    {
        if (_loadButton != null)
        {
            _loadButton.Visible = false;
        }
    }

    private void RefreshIssuesUi()
    {
        if (_issuesContainer == null)
        {
            return;
        }

        foreach (Node child in _issuesContainer.GetChildren())
        {
            child.QueueFree();
        }

        Label noteLabel = UiSceneTemplates.InstantiateMessageLabel();
        noteLabel.Modulate = new Color(0.85f, 0.7f, 0.3f, 1.0f);
        noteLabel.Text = GetPresetAssumptionText(GetSelectedObjectType(), _presetOption?.GetSelectedId() ?? 0);
        _issuesContainer.AddChild(noteLabel);
    }

    private ObjectViewer.ObjectType GetSelectedObjectType()
    {
        if (_typeOption == null)
        {
            return ObjectViewer.ObjectType.Planet;
        }

        return (ObjectViewer.ObjectType)_typeOption.GetSelectedId();
    }

    private string GetSelectedPresetLabel()
    {
        if (_presetOption == null || _presetOption.ItemCount == 0)
        {
            return "Random";
        }

        int selectedIndex = _presetOption.GetSelected();
        if (selectedIndex < 0 || selectedIndex >= _presetOption.ItemCount)
        {
            return "Random";
        }

        return _presetOption.GetItemText(selectedIndex);
    }

    private GenerationUseCaseSettings BuildUseCaseSettingsFromControls()
    {
        return BuildEnhancedUseCaseSettingsFromControls();
    }

    private static string GetPresetAssumptionText(ObjectViewer.ObjectType objectType, int presetId)
    {
        if (objectType == ObjectViewer.ObjectType.Star)
        {
            if (presetId == 1)
            {
                return "Sun-like targets a G-class star with near-solar metallicity while the rest stays deterministic.";
            }

            if (presetId == 2)
            {
                return "Red Dwarf biases toward an M-class star and leaves age and metallicity seed-driven.";
            }

            if (presetId == 3)
            {
                return "Hot Blue biases toward a luminous B-class star and remains intentionally rare.";
            }

            return "Random leaves the stellar parameter set open for a full seed-driven roll.";
        }

        if (objectType == ObjectViewer.ObjectType.Planet)
        {
            if (presetId == 1)
            {
                return "Earth-like targets a temperate terrestrial world with atmosphere present and rings disabled.";
            }

            if (presetId == 2)
            {
                return "Hot Jupiter targets a close-in gas giant while chemistry and visuals stay seed-driven.";
            }

            if (presetId == 3)
            {
                return "Cold Giant targets an outer gas giant and leaves ring complexity open.";
            }

            if (presetId == 4)
            {
                return "Mars-like biases toward a smaller cold terrestrial world with a thin-atmosphere target.";
            }

            if (presetId == 5)
            {
                return "Dwarf Planet locks a dwarf-size target with no atmosphere or rings.";
            }

            if (presetId == 6)
            {
                return "Ice Giant targets a Neptune-class world in the cold zone and prefers trace rings.";
            }

            return "Random leaves size, orbit zone, atmosphere, ring state, and the extra profile sliders open.";
        }

        if (objectType == ObjectViewer.ObjectType.Asteroid)
        {
            if (presetId == 1)
            {
                return "Carbonaceous biases toward dark, carbon-rich rock.";
            }

            if (presetId == 2)
            {
                return "Metallic biases toward dense, iron-rich material.";
            }

            if (presetId == 3)
            {
                return "Stony biases toward silicate-rich rock.";
            }

            if (presetId == 4)
            {
                return "Dark Red biases toward primitive outer-system material.";
            }

            if (presetId == 5)
            {
                return "Basaltic biases toward differentiated, brighter rock.";
            }

            if (presetId == 6)
            {
                return "Ceres-like biases toward a larger dwarf-like asteroid.";
            }

            return "Random asteroid generation leaves type, orbit band, density, and brightness open.";
        }

        if (presetId == 1)
        {
            return "Jupiter-family biases toward a shorter-period inner-system comet.";
        }

        if (presetId == 2)
        {
            return "Long-period biases toward a distant icy comet on a stretched orbit.";
        }

        if (presetId == 3)
        {
            return "Dormant keeps a comet body but biases away from active outgassing.";
        }

        if (presetId == 4)
        {
            return "Extinct biases toward a spent comet with a darker, dustier surface.";
        }

        return "Random comet generation leaves family, activity, and nucleus size open.";
    }

    private static int GenerateHiddenSeed()
    {
        long ticksUsec = unchecked((long)Time.GetTicksUsec());
        long unixTimeUsec = (long)(Time.GetUnixTimeFromSystem() * 1000000.0);
        long combined = (ticksUsec ^ unixTimeUsec) & 0x7FFFFFFF;
        if (combined < 1)
        {
            combined = 1;
        }

        return (int)combined;
    }
}
