using Godot;
using Godot.Collections;
using StarGen.App.Shared;
using StarGen.Domain.Generation;
using StarGen.Domain.Generation.Parameters;
using StarGen.Domain.Systems;
using StarGen.Services.Persistence;

namespace StarGen.App;

/// <summary>
/// Pre-launch studio for standalone system generation.
/// </summary>
public partial class SystemGenerationScreen : Control
{
	[Signal]
	public delegate void start_system_generationEventHandler(SolarSystemSpec spec);

	[Signal]
	public delegate void load_system_requestedEventHandler();

	[Signal]
	public delegate void back_requestedEventHandler();

	private VBoxContainer? _parameterVBox;
	private BoxContainer? _studioRow;
	private Control? _settingsPanel;
	private Control? _summaryPanel;
	private Label? _versionLabel;
	private Label? _summaryLabel;
	private Label? _assumptionsLabel;
	private VBoxContainer? _issuesContainer;
	private Button? _startButton;
	private Button? _loadButton;
	private Button? _backButton;
	private HBoxContainer? _seedRow;
	private SpinBox? _seedInput;
	private SpinBox? _starCountMinInput;
	private SpinBox? _starCountMaxInput;
	private LineEdit? _spectralHintsInput;
	private SpinBox? _systemAgeInput;
	private SpinBox? _systemMetallicityInput;
	private CheckBox? _includeBeltsCheck;
	private CheckBox? _generatePopulationCheck;
	private OptionButton? _rulesetModeOption;
	private CheckBox? _showTravellerReadoutsCheck;
	private HSlider? _lifePermissivenessInput;
	private Label? _lifePermissivenessValueLabel;
	private HSlider? _populationPermissivenessInput;
	private Label? _populationPermissivenessValueLabel;
	private OptionButton? _mainworldPolicyOption;
	private GenerationParameterIssueSet _currentIssues = new();
	private bool _showSeedControls;

	/// <summary>
	/// Builds the screen and initializes controls.
	/// </summary>
	public override void _Ready()
	{
		CacheNodeReferences();
		ApplyLayoutPolish();
		BuildParameterUi();
		ConnectSignals();
		ApplyVersionLabel();
		ApplyDefaults();
		ApplySeedVisibilityPreference(rerollHiddenSeed: true);
		RefreshSummary();
		ApplyResponsiveLayout();
		Resized += ApplyResponsiveLayout;
	}

	/// <summary>
	/// Applies a seed generated by the parent app.
	/// </summary>
	public void SetInitialSeed(int seedValue)
	{
		if (_seedInput != null)
		{
			_seedInput.Value = seedValue;
		}

		RefreshSummary();
	}

	/// <summary>
	/// Applies the global studio seed-visibility preference and optionally rerolls hidden seeds.
	/// </summary>
	public void ApplySeedVisibilityPreference(bool rerollHiddenSeed)
	{
		StudioUiPreferencesService.StudioUiPreferences preferences = StudioUiPreferencesService.LoadOrDefault();
		_showSeedControls = preferences.ShowSeedControls;

		if (_seedRow != null)
		{
			_seedRow.Visible = _showSeedControls;
		}

		if (_showSeedControls)
		{
			if (_seedInput != null && _seedInput.Value <= 0.0)
			{
				_seedInput.Value = 12345.0;
			}
		}
		else if (rerollHiddenSeed && _seedInput != null)
		{
			_seedInput.Value = GenerateHiddenSeed();
		}

		RefreshSummary();
	}

	/// <summary>
	/// Returns the currently selected generation spec.
	/// </summary>
	public SolarSystemSpec GetCurrentSpec()
	{
		int seedValue = _seedInput != null ? (int)_seedInput.Value : 1;
		int minStars = _starCountMinInput != null ? (int)_starCountMinInput.Value : 1;
		int maxStars = _starCountMaxInput != null ? (int)_starCountMaxInput.Value : minStars;

		SolarSystemSpec spec = new(seedValue, minStars, maxStars);
		if (_spectralHintsInput != null)
		{
			spec.SpectralClassHints = ParseSpectralHints(_spectralHintsInput.Text);
		}

		if (_systemAgeInput != null)
		{
			spec.SystemAgeYears = _systemAgeInput.Value >= 0.0 ? _systemAgeInput.Value * 1.0e9 : -1.0;
		}

		if (_systemMetallicityInput != null)
		{
			spec.SystemMetallicity = _systemMetallicityInput.Value >= 0.0 ? _systemMetallicityInput.Value : -1.0;
		}

		if (_includeBeltsCheck != null)
		{
			spec.IncludeAsteroidBelts = _includeBeltsCheck.ButtonPressed;
		}

		if (_generatePopulationCheck != null)
		{
			spec.GeneratePopulation = _generatePopulationCheck.ButtonPressed;
		}

		spec.UseCaseSettings = BuildUseCaseSettingsFromControls();
		return spec;
	}

	private void CacheNodeReferences()
	{
		const string Root = "MarginContainer/MainPanel/MarginContainer/VBox";
		_studioRow = GetNodeOrNull<BoxContainer>($"{Root}/StudioRow");
		_settingsPanel = GetNodeOrNull<Control>($"{Root}/StudioRow/SettingsPanel");
		_summaryPanel = null;
		_versionLabel = GetNodeOrNull<Label>($"{Root}/HeaderRow/VersionLabel");
		_parameterVBox = GetNodeOrNull<VBoxContainer>($"{Root}/StudioRow/SettingsPanel/MarginContainer/SettingsVBox/ScrollContainer/ParameterVBox");
		_summaryLabel = GetNodeOrNull<Label>($"{Root}/StudioRow/SettingsPanel/MarginContainer/SettingsVBox/FooterVBox/SummaryLabel");
		_assumptionsLabel = GetNodeOrNull<Label>($"{Root}/StudioRow/SettingsPanel/MarginContainer/SettingsVBox/FooterVBox/AssumptionsLabel");
		_issuesContainer = GetNodeOrNull<VBoxContainer>($"{Root}/StudioRow/SettingsPanel/MarginContainer/SettingsVBox/FooterVBox/IssuesContainer");
		_startButton = GetNodeOrNull<Button>($"{Root}/StudioRow/SettingsPanel/MarginContainer/SettingsVBox/FooterVBox/Buttons/StartButton");
		_loadButton = GetNodeOrNull<Button>($"{Root}/StudioRow/SettingsPanel/MarginContainer/SettingsVBox/FooterVBox/Buttons/LoadButton");
		_backButton = GetNodeOrNull<Button>($"{Root}/HeaderRow/BackButton");
	}

	private void BuildParameterUi()
	{
		if (_parameterVBox == null || _seedInput != null)
		{
			return;
		}

		_seedInput = AddSpinRow("Seed", 1.0, 999999.0, 1.0, "generation_seed");
		_seedRow = _seedInput.GetParent() as HBoxContainer;
		_starCountMinInput = AddSpinRow("Min Stars", 1.0, 4.0, 1.0, "star_count_min");
		_starCountMaxInput = AddSpinRow("Max Stars", 1.0, 4.0, 1.0, "star_count_max");
		_spectralHintsInput = AddLineRow("Spectral", "G,K,M", "spectral_class_hints");
		_systemAgeInput = AddSpinRow("Age (Gyr)", -1.0, 13.5, 0.1, "system_age_years");
		_systemMetallicityInput = AddSpinRow("Metallicity", -1.0, 2.0, 0.05, "system_metallicity");
		_includeBeltsCheck = AddCheckRow("Asteroid Belts", "include_asteroid_belts");
		_generatePopulationCheck = AddCheckRow("Population", "generate_population");
		_rulesetModeOption = AddOptionRow("Ruleset", "ruleset_mode");
		_rulesetModeOption.AddItem("Default", (int)GenerationUseCaseSettings.RulesetModeType.Default);
		_rulesetModeOption.AddItem("Traveller", (int)GenerationUseCaseSettings.RulesetModeType.Traveller);
		_showTravellerReadoutsCheck = AddCheckRow("Traveller Readouts", "show_traveller_readouts");
		AddPermissivenessLegend();
		_lifePermissivenessInput = AddPermissivenessRow(
			"Life Potential",
			"LifePermissivenessValue",
			"life");
		_populationPermissivenessInput = AddPermissivenessRow(
			"Settlement Density",
			"PopulationPermissivenessValue",
			"settlement");
		_mainworldPolicyOption = AddOptionRow("Mainworld", "mainworld_policy");
		_mainworldPolicyOption.AddItem("None", (int)GenerationUseCaseSettings.MainworldPolicyType.None);
		_mainworldPolicyOption.AddItem("Prefer", (int)GenerationUseCaseSettings.MainworldPolicyType.Prefer);
		_mainworldPolicyOption.AddItem("Require", (int)GenerationUseCaseSettings.MainworldPolicyType.Require);
	}

	private SpinBox AddSpinRow(string labelText, double minValue, double maxValue, double step, string parameterId)
	{
		HBoxContainer row = CreateRow(labelText, parameterId);
		SpinBox spinBox = new SpinBox();
		spinBox.MinValue = minValue;
		spinBox.MaxValue = maxValue;
		spinBox.Step = step;
		spinBox.Rounded = step >= 1.0;
		spinBox.SizeFlagsHorizontal = Control.SizeFlags.ExpandFill;
		row.AddChild(spinBox);
		return spinBox;
	}

	private LineEdit AddLineRow(string labelText, string placeholderText, string parameterId)
	{
		HBoxContainer row = CreateRow(labelText, parameterId);
		LineEdit lineEdit = new LineEdit();
		lineEdit.PlaceholderText = placeholderText;
		lineEdit.SizeFlagsHorizontal = Control.SizeFlags.ExpandFill;
		row.AddChild(lineEdit);
		return lineEdit;
	}

	private CheckBox AddCheckRow(string labelText, string parameterId)
	{
		CheckBox checkBox = new CheckBox();
		checkBox.Text = labelText;
		checkBox.TooltipText = GetAssumptionText(parameterId);
		_parameterVBox!.AddChild(checkBox);
		return checkBox;
	}

	private OptionButton AddOptionRow(string labelText, string parameterId)
	{
		HBoxContainer row = CreateRow(labelText, parameterId);
		OptionButton optionButton = new OptionButton();
		optionButton.SizeFlagsHorizontal = Control.SizeFlags.ExpandFill;
		row.AddChild(optionButton);
		return optionButton;
	}

	private void AddPermissivenessLegend()
	{
		Label legendLabel = new Label();
		legendLabel.Text = PermissivenessScaleHelper.GetLegendText();
		legendLabel.AutowrapMode = TextServer.AutowrapMode.WordSmart;
		legendLabel.CustomMinimumSize = new Vector2(220.0f, 0.0f);
		legendLabel.AddThemeFontSizeOverride("font_size", 10);
		legendLabel.Modulate = new Color(0.62f, 0.7f, 0.8f, 1.0f);
		_parameterVBox!.AddChild(legendLabel);
	}

	private HSlider AddPermissivenessRow(string labelText, string valueLabelName, string subject)
	{
		HBoxContainer row = CreateRow(labelText, $"{subject}_permissiveness");
		Label? label = row.GetChild(0) as Label;
		if (label != null)
		{
			label.CustomMinimumSize = new Vector2(120.0f, 0.0f);
			label.TooltipText = PermissivenessScaleHelper.GetTooltipText(subject);
		}

		HSlider slider = new HSlider();
		slider.MinValue = 0.0;
		slider.MaxValue = 1.0;
		slider.Step = 0.05;
		slider.SizeFlagsHorizontal = Control.SizeFlags.ExpandFill;
		if (label != null)
		{
			slider.TooltipText = label.TooltipText;
		}

		row.AddChild(slider);
		Label valueLabel = new Label();
		valueLabel.Name = valueLabelName;
		valueLabel.CustomMinimumSize = new Vector2(156.0f, 0.0f);
		valueLabel.HorizontalAlignment = HorizontalAlignment.Right;
		if (label != null)
		{
			valueLabel.TooltipText = label.TooltipText;
		}

		row.AddChild(valueLabel);

		if (valueLabelName == "LifePermissivenessValue")
		{
			_lifePermissivenessValueLabel = valueLabel;
		}
		else
		{
			_populationPermissivenessValueLabel = valueLabel;
		}

		return slider;
	}

	private HBoxContainer CreateRow(string labelText, string parameterId)
	{
		HBoxContainer row = new HBoxContainer();
		row.AddThemeConstantOverride("separation", 10);
		Label label = new Label();
		label.Text = labelText;
		label.CustomMinimumSize = new Vector2(96.0f, 0.0f);
		label.TooltipText = GetAssumptionText(parameterId);
		row.AddChild(label);
		_parameterVBox!.AddChild(row);
		return row;
	}

	private void ApplyResponsiveLayout()
	{
		StudioScreenLayoutHelper.ApplyResponsiveStudioLayout(this, _studioRow, _settingsPanel, _summaryPanel);
	}

	private void ConnectSignals()
	{
		if (_startButton != null) _startButton.Pressed += OnStartPressed;
		if (_loadButton != null) _loadButton.Pressed += () => EmitSignal(SignalName.load_system_requested);
		if (_backButton != null) _backButton.Pressed += () => EmitSignal(SignalName.back_requested);
		if (_seedInput != null) _seedInput.ValueChanged += _ => RefreshSummary();
		if (_starCountMinInput != null) _starCountMinInput.ValueChanged += _ => RefreshSummary();
		if (_starCountMaxInput != null) _starCountMaxInput.ValueChanged += _ => RefreshSummary();
		if (_spectralHintsInput != null) _spectralHintsInput.TextChanged += _ => RefreshSummary();
		if (_systemAgeInput != null) _systemAgeInput.ValueChanged += _ => RefreshSummary();
		if (_systemMetallicityInput != null) _systemMetallicityInput.ValueChanged += _ => RefreshSummary();
		if (_includeBeltsCheck != null) _includeBeltsCheck.Toggled += _ => RefreshSummary();
		if (_generatePopulationCheck != null) _generatePopulationCheck.Toggled += _ => RefreshSummary();
		if (_showTravellerReadoutsCheck != null) _showTravellerReadoutsCheck.Toggled += _ => RefreshSummary();
		if (_lifePermissivenessInput != null) _lifePermissivenessInput.ValueChanged += OnLifePermissivenessChanged;
		if (_populationPermissivenessInput != null) _populationPermissivenessInput.ValueChanged += OnPopulationPermissivenessChanged;
		if (_mainworldPolicyOption != null) _mainworldPolicyOption.ItemSelected += _ => RefreshSummary();
		if (_rulesetModeOption != null) _rulesetModeOption.ItemSelected += OnRulesetModeSelected;
	}

	private void ApplyVersionLabel()
	{
		if (_versionLabel != null)
		{
			string version = ProjectSettings.GetSetting("application/config/version", "0.5.0.0").AsString();
			_versionLabel.Text = $"Version {version}";
		}
	}

	private void ApplyDefaults()
	{
		if (_seedInput != null) _seedInput.Value = 12345.0;
		if (_starCountMinInput != null) _starCountMinInput.Value = 1.0;
		if (_starCountMaxInput != null) _starCountMaxInput.Value = 1.0;
		if (_systemAgeInput != null) _systemAgeInput.Value = -1.0;
		if (_systemMetallicityInput != null) _systemMetallicityInput.Value = -1.0;
		if (_includeBeltsCheck != null) _includeBeltsCheck.ButtonPressed = true;
		if (_generatePopulationCheck != null) _generatePopulationCheck.ButtonPressed = false;
		if (_rulesetModeOption != null) _rulesetModeOption.Select((int)GenerationUseCaseSettings.RulesetModeType.Default);
		if (_showTravellerReadoutsCheck != null) _showTravellerReadoutsCheck.ButtonPressed = false;
		if (_lifePermissivenessInput != null) _lifePermissivenessInput.Value = GenerationUseCaseSettings.NeutralPermissiveness;
		if (_populationPermissivenessInput != null) _populationPermissivenessInput.Value = GenerationUseCaseSettings.NeutralPermissiveness;
		if (_mainworldPolicyOption != null) _mainworldPolicyOption.Select((int)GenerationUseCaseSettings.MainworldPolicyType.None);
		UpdatePermissivenessValueLabels();
	}

	private void OnStartPressed()
	{
		RefreshSummary();
		if (_currentIssues.HasErrors())
		{
			return;
		}

		if (!_showSeedControls && _seedInput != null)
		{
			_seedInput.Value = GenerateHiddenSeed();
		}

		EmitSignal(SignalName.start_system_generation, GetCurrentSpec());
	}

	private void OnRulesetModeSelected(long selectedId)
	{
		if (selectedId == (long)GenerationUseCaseSettings.RulesetModeType.Traveller)
		{
			if (_showTravellerReadoutsCheck != null)
			{
				_showTravellerReadoutsCheck.ButtonPressed = true;
			}

			if (_mainworldPolicyOption != null)
			{
				_mainworldPolicyOption.Select((int)GenerationUseCaseSettings.MainworldPolicyType.Require);
			}

			if (_generatePopulationCheck != null)
			{
				_generatePopulationCheck.ButtonPressed = true;
			}

			ApplyTravellerDefaultsToControls();
		}

		RefreshSummary();
	}

	private void RefreshSummary()
	{
		SolarSystemSpec spec = GetCurrentSpec();
		_currentIssues = SystemGenerationParameterValidator.Validate(spec);

		if (_summaryLabel != null)
		{
			string hintsText = spec.SpectralClassHints.Count > 0 ? FormatSpectralHints(spec.SpectralClassHints) : "Any";
			System.Collections.Generic.List<string> lines = new();
			if (_showSeedControls)
			{
				lines.Add($"Seed {spec.GenerationSeed}");
			}

			lines.Add($"Stars {spec.StarCountMin}-{spec.StarCountMax}");
			lines.Add($"Spectral {hintsText}");
			lines.Add($"Belts {(spec.IncludeAsteroidBelts ? "On" : "Off")}");
			lines.Add($"Population {(spec.GeneratePopulation ? "On" : "Off")}");
			lines.Add($"Ruleset {spec.UseCaseSettings.RulesetMode}");
			lines.Add($"Life Potential {PermissivenessScaleHelper.GetBandLabel(spec.UseCaseSettings.LifePermissiveness)}");
			lines.Add($"Settlement Density {PermissivenessScaleHelper.GetBandLabel(spec.UseCaseSettings.PopulationPermissiveness)}");
			_summaryLabel.Text = string.Join("\n", lines);
		}

		if (_assumptionsLabel != null)
		{
			_assumptionsLabel.Text = string.Empty;
			_assumptionsLabel.TooltipText = "Traveller mode raises the settlement-density assumption, enables Traveller readouts, and requires a mainworld candidate when possible while leaving non-Traveller system details to the normal deterministic generator.";
		}

		RefreshIssuesUi();
	}

	private void RefreshIssuesUi()
	{
		if (_issuesContainer == null)
		{
			return;
		}

		foreach (Node child in _issuesContainer.GetChildren())
		{
			child.QueueFree();
		}

		if (_currentIssues.Issues.Count == 0)
		{
			Label label = new Label();
			label.Text = "No parameter issues.";
			label.Modulate = new Color(0.55f, 0.75f, 0.55f, 1.0f);
			_issuesContainer.AddChild(label);
			return;
		}

		foreach (GenerationParameterIssue issue in _currentIssues.Issues)
		{
			Label label = new Label();
			label.AutowrapMode = TextServer.AutowrapMode.Word;
			label.CustomMinimumSize = new Vector2(220.0f, 0.0f);
			if (issue.Severity == GenerationParameterIssue.IssueSeverity.Error)
			{
				label.Modulate = new Color(1.0f, 0.45f, 0.45f, 1.0f);
				label.Text = $"Error: {issue.Message}";
			}
			else
			{
				label.Modulate = new Color(0.85f, 0.7f, 0.3f, 1.0f);
				label.Text = $"Warning: {issue.Message}";
			}

			_issuesContainer.AddChild(label);
		}
	}

	private GenerationUseCaseSettings BuildUseCaseSettingsFromControls()
	{
		GenerationUseCaseSettings settings = GenerationUseCaseSettings.CreateDefault();
		if (_rulesetModeOption != null)
		{
			settings.RulesetMode = (GenerationUseCaseSettings.RulesetModeType)_rulesetModeOption.GetSelectedId();
		}

		if (_showTravellerReadoutsCheck != null)
		{
			settings.ShowTravellerReadouts = _showTravellerReadoutsCheck.ButtonPressed;
		}

		if (_lifePermissivenessInput != null)
		{
			settings.LifePermissiveness = _lifePermissivenessInput.Value;
		}

		if (_populationPermissivenessInput != null)
		{
			settings.PopulationPermissiveness = _populationPermissivenessInput.Value;
		}

		if (_mainworldPolicyOption != null)
		{
			settings.MainworldPolicy = (GenerationUseCaseSettings.MainworldPolicyType)_mainworldPolicyOption.GetSelectedId();
		}

		return settings;
	}

	private void ApplyTravellerDefaultsToControls()
	{
		if (_lifePermissivenessInput != null)
		{
			if (System.Math.Abs(_lifePermissivenessInput.Value - GenerationUseCaseSettings.NeutralPermissiveness) < 0.001)
			{
				_lifePermissivenessInput.Value = GenerationUseCaseSettings.TravellerLifePermissiveness;
			}
		}

		if (_populationPermissivenessInput != null)
		{
			if (System.Math.Abs(_populationPermissivenessInput.Value - GenerationUseCaseSettings.NeutralPermissiveness) < 0.001)
			{
				_populationPermissivenessInput.Value = GenerationUseCaseSettings.TravellerPopulationPermissiveness;
			}
		}
	}

	private void OnLifePermissivenessChanged(double _value)
	{
		UpdatePermissivenessValueLabels();
		RefreshSummary();
	}

	private void OnPopulationPermissivenessChanged(double _value)
	{
		UpdatePermissivenessValueLabels();
		RefreshSummary();
	}

	private void UpdatePermissivenessValueLabels()
	{
		if (_lifePermissivenessInput != null && _lifePermissivenessValueLabel != null)
		{
			_lifePermissivenessValueLabel.Text =
				$"{_lifePermissivenessInput.Value:0.00} {PermissivenessScaleHelper.GetBandLabel(_lifePermissivenessInput.Value)}";
		}

		if (_populationPermissivenessInput != null && _populationPermissivenessValueLabel != null)
		{
			_populationPermissivenessValueLabel.Text =
				$"{_populationPermissivenessInput.Value:0.00} {PermissivenessScaleHelper.GetBandLabel(_populationPermissivenessInput.Value)}";
		}
	}

	private static int GenerateHiddenSeed()
	{
		long ticksUsec = unchecked((long)Time.GetTicksUsec());
		long unixTimeUsec = (long)(Time.GetUnixTimeFromSystem() * 1000000.0);
		long combined = (ticksUsec ^ unixTimeUsec) & 0x7FFFFFFF;
		if (combined < 1)
		{
			combined = 1;
		}

		return (int)combined;
	}

	private void ApplyLayoutPolish()
	{
		if (_summaryLabel != null)
		{
			_summaryLabel.Visible = false;
		}

		if (_assumptionsLabel != null)
		{
			_assumptionsLabel.Visible = false;
		}
	}

	private string GetAssumptionText(string parameterId)
	{
		foreach (GenerationParameterDefinition definition in GenerationParameterCatalog.GetSystemDefinitions())
		{
			if (definition.Id == parameterId)
			{
				return definition.AssumptionText;
			}
		}

		return string.Empty;
	}

	private static Array<int> ParseSpectralHints(string text)
	{
		Array<int> result = new();
		if (string.IsNullOrWhiteSpace(text))
		{
			return result;
		}

		string[] parts = text.Split(',', System.StringSplitOptions.RemoveEmptyEntries | System.StringSplitOptions.TrimEntries);
		foreach (string rawPart in parts)
		{
			string part = rawPart.ToUpperInvariant();
			if (part == "O") result.Add((int)StarClass.SpectralClass.O);
			else if (part == "B") result.Add((int)StarClass.SpectralClass.B);
			else if (part == "A") result.Add((int)StarClass.SpectralClass.A);
			else if (part == "F") result.Add((int)StarClass.SpectralClass.F);
			else if (part == "G") result.Add((int)StarClass.SpectralClass.G);
			else if (part == "K") result.Add((int)StarClass.SpectralClass.K);
			else if (part == "M") result.Add((int)StarClass.SpectralClass.M);
		}

		return result;
	}

	private static string FormatSpectralHints(Array<int> hints)
	{
		if (hints.Count == 0)
		{
			return "Any";
		}

		System.Collections.Generic.List<string> parts = new();
		foreach (int hint in hints)
		{
			if (System.Enum.IsDefined(typeof(StarClass.SpectralClass), hint))
			{
				parts.Add(((StarClass.SpectralClass)hint).ToString());
			}
		}

		return string.Join(", ", parts);
	}
}
