using Godot;
using Godot.Collections;
using StarGen.App.Components;
using StarGen.App.Shared;
using StarGen.Domain.Generation;
using StarGen.Domain.Generation.Parameters;
using StarGen.Domain.Systems;
using StarGen.Services.Persistence;

namespace StarGen.App;

/// <summary>
/// Pre-launch studio for standalone system generation.
/// </summary>
public partial class SystemGenerationScreen : Control
{
	[Signal]
	public delegate void start_system_generationEventHandler(SolarSystemSpec spec);

	[Signal]
	public delegate void back_requestedEventHandler();

	private VBoxContainer? _parameterVBox;
	private BoxContainer? _studioRow;
	private Control? _settingsPanel;
	private Control? _rulesPanel;
	private Control? _summaryPanel;
	private Label? _versionLabel;
	private Label? _summaryLabel;
	private Label? _assumptionsLabel;
	private VBoxContainer? _issuesContainer;
	private Button? _startButton;
	private Button? _loadButton;
	private Button? _backButton;
	private HBoxContainer? _seedRow;
	private SpinBox? _seedInput;
	private SpinBox? _starCountMinInput;
	private SpinBox? _starCountMaxInput;
	private LineEdit? _spectralHintsInput;
	private SpinBox? _systemAgeInput;
	private SpinBox? _systemMetallicityInput;
	private CheckBox? _includeBeltsCheck;
	private OptionButton? _rulesetModeOption;
	private CheckBox? _showTravellerReadoutsCheck;
	private CheckBox? _forceLifeOnSupportableWorldsCheck;
	private HBoxContainer? _temperateWorldBiasRow;
	private HSlider? _temperateWorldBiasInput;
	private Label? _temperateWorldBiasValueLabel;
	private HBoxContainer? _harshWorldBiasRow;
	private HSlider? _harshWorldBiasInput;
	private Label? _harshWorldBiasValueLabel;
	private HBoxContainer? _terrestrialWorldBiasRow;
	private HSlider? _terrestrialWorldBiasInput;
	private Label? _terrestrialWorldBiasValueLabel;
	private HBoxContainer? _nativeLifeBiasRow;
	private HSlider? _nativeLifeBiasInput;
	private Label? _nativeLifeBiasValueLabel;
	private HSlider? _populationPermissivenessInput;
	private Label? _populationPermissivenessValueLabel;
	private HBoxContainer? _populationPermissivenessRow;
	private HBoxContainer? _mainworldPolicyRow;
	private OptionButton? _mainworldPolicyOption;
	private GenerationParameterIssueSet _currentIssues = new();
	private bool _showSeedControls;

	/// <summary>
	/// Builds the screen and initializes controls.
	/// </summary>
	public override void _Ready()
	{
		CacheNodeReferences();
		ApplyLayoutPolish();
		ConnectSignals();
		ApplyVersionLabel();
		ApplyDefaults();
		ApplyStellarParameterTooltips();
		ApplyPlanetaryParameterTooltips();
		ApplyLifeParameterTooltips();
		InitializeScienceHelpUi();
		ApplySeedVisibilityPreference(rerollHiddenSeed: true);
		RefreshSummary();
		ApplyResponsiveLayout();
		Resized += ApplyResponsiveLayout;
	}

	/// <summary>
	/// Applies a seed generated by the parent app.
	/// </summary>
	public void SetInitialSeed(int seedValue)
	{
		if (_seedInput != null)
		{
			_seedInput.Value = seedValue;
		}

		RefreshSummary();
	}

	/// <summary>
	/// Applies the global studio seed-visibility preference and optionally rerolls hidden seeds.
	/// </summary>
	public void ApplySeedVisibilityPreference(bool rerollHiddenSeed)
	{
		StudioUiPreferencesService.StudioUiPreferences preferences = StudioUiPreferencesService.LoadOrDefault();
		_showSeedControls = preferences.ShowSeedControls;

		if (_seedRow != null)
		{
			_seedRow.Visible = _showSeedControls;
		}

		if (_showSeedControls)
		{
			if (_seedInput != null && _seedInput.Value <= 0.0)
			{
				_seedInput.Value = 12345.0;
			}
		}
		else if (rerollHiddenSeed && _seedInput != null)
		{
			_seedInput.Value = GenerateHiddenSeed();
		}

		RefreshSummary();
	}

	/// <summary>
	/// Returns the currently selected generation spec.
	/// </summary>
	public SolarSystemSpec GetCurrentSpec()
	{
		int seedValue = _seedInput != null ? (int)_seedInput.Value : 1;
		int minStars = _starCountMinInput != null ? (int)_starCountMinInput.Value : 1;
		int maxStars = _starCountMaxInput != null ? (int)_starCountMaxInput.Value : minStars;

		SolarSystemSpec spec = new(seedValue, minStars, maxStars);
		if (_spectralHintsInput != null)
		{
			spec.SpectralClassHints = ParseSpectralHints(_spectralHintsInput.Text);
		}

		if (_systemAgeInput != null)
		{
			spec.SystemAgeYears = _systemAgeInput.Value >= 0.0 ? _systemAgeInput.Value * 1.0e9 : -1.0;
		}

		if (_systemMetallicityInput != null)
		{
			spec.SystemMetallicity = _systemMetallicityInput.Value >= 0.0 ? _systemMetallicityInput.Value : -1.0;
		}

		if (_includeBeltsCheck != null)
		{
			spec.IncludeAsteroidBelts = _includeBeltsCheck.ButtonPressed;
		}

		spec.UseCaseSettings = BuildUseCaseSettingsFromControls();
		spec.StellarProfile = BuildStellarProfileFromControls();
		spec.PlanetaryProfile = BuildPlanetaryProfileFromControls();
		return spec;
	}

	private void CacheNodeReferences()
	{
		const string Root = "MarginContainer/ScrollContainer/Layout/MainPanel/MarginContainer/VBox";
		const string HeroRoot = "MarginContainer/ScrollContainer/Layout/HeroPanel/MarginContainer/HeroVBox";
		_studioRow = GetNodeOrNull<BoxContainer>($"{Root}/StudioRow");
		_settingsPanel = GetNodeOrNull<Control>($"{Root}/StudioRow/SettingsPanel");
		_rulesPanel = GetNodeOrNull<Control>($"{Root}/StudioRow/RulesPanel");
		_summaryPanel = GetNodeOrNull<Control>($"{Root}/StudioRow/SummaryPanel");
		_versionLabel = GetNodeOrNull<Label>($"{HeroRoot}/HeaderRow/VersionLabel");
		_parameterVBox = GetNodeOrNull<VBoxContainer>($"{Root}/StudioRow/SettingsPanel/MarginContainer/SettingsVBox/ScrollContainer/ParameterVBox");
		_summaryLabel = GetNodeOrNull<Label>($"{Root}/StudioRow/SummaryPanel/MarginContainer/SummaryVBox/SummaryScroll/SummaryContent/SummaryLabel");
		_assumptionsLabel = GetNodeOrNull<Label>($"{Root}/StudioRow/SummaryPanel/MarginContainer/SummaryVBox/SummaryScroll/SummaryContent/AssumptionsLabel");
		_issuesContainer = GetNodeOrNull<VBoxContainer>($"{Root}/StudioRow/SummaryPanel/MarginContainer/SummaryVBox/SummaryScroll/SummaryContent/IssuesContainer");
		_startButton = GetNodeOrNull<Button>($"{Root}/StudioRow/SummaryPanel/MarginContainer/SummaryVBox/Buttons/StartButton");
		_loadButton = GetNodeOrNull<Button>($"{Root}/StudioRow/SummaryPanel/MarginContainer/SummaryVBox/Buttons/LoadButton");
		_backButton = GetNodeOrNull<Button>($"{HeroRoot}/HeaderRow/BackButton");
		_seedRow = GetNodeOrNull<HBoxContainer>($"{Root}/StudioRow/SettingsPanel/MarginContainer/SettingsVBox/ScrollContainer/ParameterVBox/SeedRow");
		_seedInput = GetNodeOrNull<SpinBox>($"{Root}/StudioRow/SettingsPanel/MarginContainer/SettingsVBox/ScrollContainer/ParameterVBox/SeedRow/SeedInput");
		_starCountMinInput = GetNodeOrNull<SpinBox>($"{Root}/StudioRow/SettingsPanel/MarginContainer/SettingsVBox/ScrollContainer/ParameterVBox/StarCountMinRow/StarCountMinInput");
		_starCountMaxInput = GetNodeOrNull<SpinBox>($"{Root}/StudioRow/SettingsPanel/MarginContainer/SettingsVBox/ScrollContainer/ParameterVBox/StarCountMaxRow/StarCountMaxInput");
		_spectralHintsInput = GetNodeOrNull<LineEdit>($"{Root}/StudioRow/SettingsPanel/MarginContainer/SettingsVBox/ScrollContainer/ParameterVBox/SpectralHintsRow/SpectralHintsInput");
		_systemAgeInput = GetNodeOrNull<SpinBox>($"{Root}/StudioRow/SettingsPanel/MarginContainer/SettingsVBox/ScrollContainer/ParameterVBox/SystemAgeRow/SystemAgeInput");
		_systemMetallicityInput = GetNodeOrNull<SpinBox>($"{Root}/StudioRow/SettingsPanel/MarginContainer/SettingsVBox/ScrollContainer/ParameterVBox/SystemMetallicityRow/SystemMetallicityInput");
		_includeBeltsCheck = GetNodeOrNull<CheckBox>($"{Root}/StudioRow/SettingsPanel/MarginContainer/SettingsVBox/ScrollContainer/ParameterVBox/IncludeBeltsCheck");
		_rulesetModeOption = GetNodeOrNull<OptionButton>($"{Root}/StudioRow/RulesPanel/MarginContainer/RulesVBox/ScrollContainer/RulesContent/RulesetModeRow/RulesetModeOption");
		_showTravellerReadoutsCheck = GetNodeOrNull<CheckBox>($"{Root}/StudioRow/RulesPanel/MarginContainer/RulesVBox/ScrollContainer/RulesContent/ShowTravellerReadoutsCheck");
		_forceLifeOnSupportableWorldsCheck = GetNodeOrNull<CheckBox>($"{Root}/StudioRow/RulesPanel/MarginContainer/RulesVBox/ScrollContainer/RulesContent/ForceLifeOnSupportableWorldsCheck");
		_temperateWorldBiasRow = GetNodeOrNull<HBoxContainer>($"{Root}/StudioRow/RulesPanel/MarginContainer/RulesVBox/ScrollContainer/RulesContent/TemperateWorldBiasRow");
		_temperateWorldBiasInput = GetNodeOrNull<HSlider>($"{Root}/StudioRow/RulesPanel/MarginContainer/RulesVBox/ScrollContainer/RulesContent/TemperateWorldBiasRow/TemperateWorldBiasInput");
		_temperateWorldBiasValueLabel = GetNodeOrNull<Label>($"{Root}/StudioRow/RulesPanel/MarginContainer/RulesVBox/ScrollContainer/RulesContent/TemperateWorldBiasRow/TemperateWorldBiasValue");
		_harshWorldBiasRow = GetNodeOrNull<HBoxContainer>($"{Root}/StudioRow/RulesPanel/MarginContainer/RulesVBox/ScrollContainer/RulesContent/HarshWorldBiasRow");
		_harshWorldBiasInput = GetNodeOrNull<HSlider>($"{Root}/StudioRow/RulesPanel/MarginContainer/RulesVBox/ScrollContainer/RulesContent/HarshWorldBiasRow/HarshWorldBiasInput");
		_harshWorldBiasValueLabel = GetNodeOrNull<Label>($"{Root}/StudioRow/RulesPanel/MarginContainer/RulesVBox/ScrollContainer/RulesContent/HarshWorldBiasRow/HarshWorldBiasValue");
		_terrestrialWorldBiasRow = GetNodeOrNull<HBoxContainer>($"{Root}/StudioRow/RulesPanel/MarginContainer/RulesVBox/ScrollContainer/RulesContent/TerrestrialWorldBiasRow");
		_terrestrialWorldBiasInput = GetNodeOrNull<HSlider>($"{Root}/StudioRow/RulesPanel/MarginContainer/RulesVBox/ScrollContainer/RulesContent/TerrestrialWorldBiasRow/TerrestrialWorldBiasInput");
		_terrestrialWorldBiasValueLabel = GetNodeOrNull<Label>($"{Root}/StudioRow/RulesPanel/MarginContainer/RulesVBox/ScrollContainer/RulesContent/TerrestrialWorldBiasRow/TerrestrialWorldBiasValue");
		_nativeLifeBiasRow = GetNodeOrNull<HBoxContainer>($"{Root}/StudioRow/RulesPanel/MarginContainer/RulesVBox/ScrollContainer/RulesContent/NativeLifeBiasRow");
		_nativeLifeBiasInput = GetNodeOrNull<HSlider>($"{Root}/StudioRow/RulesPanel/MarginContainer/RulesVBox/ScrollContainer/RulesContent/NativeLifeBiasRow/NativeLifeBiasInput");
		_nativeLifeBiasValueLabel = GetNodeOrNull<Label>($"{Root}/StudioRow/RulesPanel/MarginContainer/RulesVBox/ScrollContainer/RulesContent/NativeLifeBiasRow/NativeLifeBiasValue");
		_populationPermissivenessRow = GetNodeOrNull<HBoxContainer>($"{Root}/StudioRow/RulesPanel/MarginContainer/RulesVBox/ScrollContainer/RulesContent/PopulationPermissivenessRow");
		_populationPermissivenessInput = GetNodeOrNull<HSlider>($"{Root}/StudioRow/RulesPanel/MarginContainer/RulesVBox/ScrollContainer/RulesContent/PopulationPermissivenessRow/PopulationPermissivenessInput");
		_populationPermissivenessValueLabel = GetNodeOrNull<Label>($"{Root}/StudioRow/RulesPanel/MarginContainer/RulesVBox/ScrollContainer/RulesContent/PopulationPermissivenessRow/PopulationPermissivenessValue");
		_mainworldPolicyRow = GetNodeOrNull<HBoxContainer>($"{Root}/StudioRow/RulesPanel/MarginContainer/RulesVBox/ScrollContainer/RulesContent/MainworldPolicyRow");
		_mainworldPolicyOption = GetNodeOrNull<OptionButton>($"{Root}/StudioRow/RulesPanel/MarginContainer/RulesVBox/ScrollContainer/RulesContent/MainworldPolicyRow/MainworldPolicyOption");
		CacheStellarNodeReferences();
		CachePlanetaryNodeReferences();
		CacheLifeNodeReferences();
		CacheScienceHelpNodeReferences();
	}

	private void ApplyResponsiveLayout()
	{
		StudioScreenLayoutHelper.ApplyResponsiveStudioLayout(this, _studioRow, _settingsPanel, _rulesPanel, _summaryPanel);
	}

	private void ConnectSignals()
	{
		if (_startButton != null) _startButton.Pressed += OnStartPressed;
		if (_backButton != null) _backButton.Pressed += () => EmitSignal(SignalName.back_requested);
		if (_seedInput != null) _seedInput.ValueChanged += _ => RefreshSummary();
		if (_starCountMinInput != null) _starCountMinInput.ValueChanged += _ => RefreshSummary();
		if (_starCountMaxInput != null) _starCountMaxInput.ValueChanged += _ => RefreshSummary();
		if (_spectralHintsInput != null) _spectralHintsInput.TextChanged += _ => RefreshSummary();
		if (_systemAgeInput != null) _systemAgeInput.ValueChanged += _ => RefreshSummary();
		if (_systemMetallicityInput != null) _systemMetallicityInput.ValueChanged += _ => RefreshSummary();
		if (_includeBeltsCheck != null) _includeBeltsCheck.Toggled += _ => RefreshSummary();
		if (_showTravellerReadoutsCheck != null) _showTravellerReadoutsCheck.Toggled += _ => RefreshSummary();
		if (_forceLifeOnSupportableWorldsCheck != null) _forceLifeOnSupportableWorldsCheck.Toggled += _ => RefreshSummary();
		if (_mainworldPolicyOption != null) _mainworldPolicyOption.ItemSelected += _ => RefreshSummary();
		if (_temperateWorldBiasInput != null) _temperateWorldBiasInput.ValueChanged += OnCompatibilityPressureChanged;
		if (_harshWorldBiasInput != null) _harshWorldBiasInput.ValueChanged += OnCompatibilityPressureChanged;
		if (_terrestrialWorldBiasInput != null) _terrestrialWorldBiasInput.ValueChanged += OnCompatibilityPressureChanged;
		if (_nativeLifeBiasInput != null) _nativeLifeBiasInput.ValueChanged += OnCompatibilityPressureChanged;
		if (_populationPermissivenessInput != null) _populationPermissivenessInput.ValueChanged += OnCompatibilityPressureChanged;
		if (_rulesetModeOption != null) _rulesetModeOption.ItemSelected += OnRulesetModeSelected;
		ConnectStellarSignals();
		ConnectPlanetarySignals();
		ConnectLifeSignals();
		ConnectScienceHelpSignals();
	}

	private void ApplyVersionLabel()
	{
		if (_versionLabel != null)
		{
			string version = UserFacingVersionHelper.GetDisplayVersion();
			_versionLabel.Text = $"Version {version}";
		}
	}

	private void ApplyDefaults()
	{
		if (_rulesetModeOption != null)
		{
			GenerationUseCasePresentation.PopulateRulesetOptions(_rulesetModeOption);
		}

		ApplyStellarDefaults();
		ApplyPlanetaryDefaults();
		ApplyLifeDefaults();
	}

	private void OnStartPressed()
	{
		RefreshSummary();
		if (_currentIssues.HasErrors())
		{
			return;
		}

		if (!_showSeedControls && _seedInput != null)
		{
			_seedInput.Value = GenerateHiddenSeed();
		}

		EmitSignal(SignalName.start_system_generation, GetCurrentSpec());
	}

	private void OnRulesetModeSelected(long selectedId)
	{
		GenerationUseCaseSettings rulesetDefaults = GenerationUseCaseSettings.CreateDefault();
		rulesetDefaults.RulesetMode = (GenerationUseCaseSettings.RulesetModeType)selectedId;
		rulesetDefaults.ApplyRulesetDefaults();
		RpgCompatibilityProfile compatibilityProfile = rulesetDefaults.GetCompatibilityProfile();

		if (_showTravellerReadoutsCheck != null)
		{
			_showTravellerReadoutsCheck.ButtonPressed = compatibilityProfile.UsesUwpLikeReadouts;
		}

		ApplyRulesetDefaultsToControls(rulesetDefaults);
		if (!compatibilityProfile.IsActive)
		{
			UpdateCompatibilityOverrideVisibility(rulesetDefaults);
		}
		RefreshSummary();
	}

	private void RefreshSummary()
	{
		SolarSystemSpec spec = GetCurrentSpec();
		_currentIssues = SystemGenerationParameterValidator.Validate(spec);

		if (_summaryLabel != null)
		{
			string hintsText = spec.SpectralClassHints.Count > 0 ? FormatSpectralHints(spec.SpectralClassHints) : "Any";
			System.Collections.Generic.List<string> lines = new();
			if (_showSeedControls)
			{
				lines.Add($"Seed {spec.GenerationSeed}");
			}

			lines.Add($"Stars {spec.StarCountMin}-{spec.StarCountMax}");
			lines.Add($"Spectral {hintsText}");
			lines.Add(BuildStellarProfileSummary(BuildStellarProfileFromControls()));
			lines.Add(BuildPlanetaryProfileSummary(BuildPlanetaryProfileFromControls()));
			lines.Add($"Belts {(spec.IncludeAsteroidBelts ? "On" : "Off")}");
			lines.Add($"Ruleset {GenerationUseCasePresentation.GetRulesetLabel(spec.UseCaseSettings.RulesetMode)}");
			lines.Add($"Life Framework {LifeScienceReferenceCatalog.GetFrameworkLabel(spec.UseCaseSettings.LifeFramework)}");
			lines.Add($"Abiogenesis {LifeScienceReferenceCatalog.GetAbiogenesisLabel(spec.UseCaseSettings.AbiogenesisModel)} | Complex Life {LifeScienceReferenceCatalog.GetComplexLifeLabel(spec.UseCaseSettings.ComplexLifeModel)}");
			lines.Add($"Civilization {LifeScienceReferenceCatalog.GetCivilizationLabel(spec.UseCaseSettings.CivilizationModel)} | Window Weight {LifeScienceReferenceCatalog.GetEnvironmentalWindowWeightLabel(spec.UseCaseSettings.EnvironmentalWindowWeight)}");
			lines.Add($"Force Life On Supportable Worlds {(spec.UseCaseSettings.ForceLifeOnSupportableWorlds ? "On" : "Off")}");
			if (spec.UseCaseSettings.RulesetMode == GenerationUseCaseSettings.RulesetModeType.Traveller)
			{
				lines.Add($"Space Opera Overrides Mainworld {spec.UseCaseSettings.MainworldPolicy} | Temperate {spec.UseCaseSettings.CompatibilityTemperateSlotFillMultiplier:0.00}x | Harsh {spec.UseCaseSettings.CompatibilityHarshSlotFillMultiplier:0.00}x");
				lines.Add($"Mainworld Class {spec.UseCaseSettings.CompatibilityTerrestrialWorldWeightMultiplier:0.00}x | Native Life {spec.UseCaseSettings.CompatibilityNativeLifeProbabilityMultiplier:0.00}x | Settlements {spec.UseCaseSettings.CompatibilityColonyProbabilityMultiplier:0.00}x");
			}
			_summaryLabel.Text = string.Join("\n", lines);
		}

		if (_assumptionsLabel != null)
		{
			_assumptionsLabel.Text = string.Empty;
		}

		RefreshIssuesUi();
	}

	private void RefreshIssuesUi()
	{
		if (_issuesContainer == null)
		{
			return;
		}

		foreach (Node child in _issuesContainer.GetChildren())
		{
			child.QueueFree();
		}

		if (_currentIssues.Issues.Count == 0)
		{
			Label label = UiSceneTemplates.InstantiateMessageLabel();
			label.Text = "No parameter issues.";
			label.Modulate = new Color(0.55f, 0.75f, 0.55f, 1.0f);
			_issuesContainer.AddChild(label);
			return;
		}

		foreach (GenerationParameterIssue issue in _currentIssues.Issues)
		{
			Label label = UiSceneTemplates.InstantiateMessageLabel();
			if (issue.Severity == GenerationParameterIssue.IssueSeverity.Error)
			{
				label.Modulate = new Color(1.0f, 0.45f, 0.45f, 1.0f);
				label.Text = $"Error: {issue.Message}";
			}
			else
			{
				label.Modulate = new Color(0.85f, 0.7f, 0.3f, 1.0f);
				label.Text = $"Warning: {issue.Message}";
			}

			_issuesContainer.AddChild(label);
		}
	}

	private GenerationUseCaseSettings BuildUseCaseSettingsFromControls()
	{
		GenerationUseCaseSettings settings = GenerationUseCaseSettings.CreateDefault();
		if (_rulesetModeOption != null)
		{
			settings.RulesetMode = (GenerationUseCaseSettings.RulesetModeType)_rulesetModeOption.GetSelectedId();
		}

		if (_showTravellerReadoutsCheck != null)
		{
			settings.ShowTravellerReadouts = _showTravellerReadoutsCheck.ButtonPressed;
		}

		if (_forceLifeOnSupportableWorldsCheck != null)
		{
			settings.ForceLifeOnSupportableWorlds = _forceLifeOnSupportableWorldsCheck.ButtonPressed;
		}

		ApplyLifeSettingsFromControls(settings);

		if (_mainworldPolicyOption != null)
		{
			settings.MainworldPolicy = (GenerationUseCaseSettings.MainworldPolicyType)_mainworldPolicyOption.GetSelectedId();
		}

		if (_temperateWorldBiasInput != null)
		{
			settings.CompatibilityTemperateSlotFillMultiplier = _temperateWorldBiasInput.Value;
		}

		if (_harshWorldBiasInput != null)
		{
			settings.CompatibilityHarshSlotFillMultiplier = _harshWorldBiasInput.Value;
		}

		if (_terrestrialWorldBiasInput != null)
		{
			settings.CompatibilityTerrestrialWorldWeightMultiplier = _terrestrialWorldBiasInput.Value;
		}

		if (_nativeLifeBiasInput != null)
		{
			settings.CompatibilityNativeLifeProbabilityMultiplier = _nativeLifeBiasInput.Value;
		}

		if (_populationPermissivenessInput != null)
		{
			settings.CompatibilityColonyProbabilityMultiplier = _populationPermissivenessInput.Value;
		}

		if (settings.GetCompatibilityProfile().UsesUwpLikeReadouts)
		{
			settings.ShowTravellerReadouts = true;
		}

		return settings;
	}

	private void ApplyTravellerDefaultsToControls()
	{
		GenerationUseCaseSettings settings = GenerationUseCaseSettings.CreateDefault();
		settings.RulesetMode = GenerationUseCaseSettings.RulesetModeType.Traveller;
		settings.ApplyRulesetDefaults();
		ApplyRulesetDefaultsToControls(settings);
	}

	private void ApplyRulesetDefaultsToControls(GenerationUseCaseSettings settings)
	{
		ApplyLifeSettingsToControls(settings);
		if (_mainworldPolicyOption != null)
		{
			_mainworldPolicyOption.Select((int)settings.MainworldPolicy);
		}

		SetCompatibilitySliderValue(_temperateWorldBiasInput, _temperateWorldBiasValueLabel, settings.CompatibilityTemperateSlotFillMultiplier);
		SetCompatibilitySliderValue(_harshWorldBiasInput, _harshWorldBiasValueLabel, settings.CompatibilityHarshSlotFillMultiplier);
		SetCompatibilitySliderValue(_terrestrialWorldBiasInput, _terrestrialWorldBiasValueLabel, settings.CompatibilityTerrestrialWorldWeightMultiplier);
		SetCompatibilitySliderValue(_nativeLifeBiasInput, _nativeLifeBiasValueLabel, settings.CompatibilityNativeLifeProbabilityMultiplier);
		SetCompatibilitySliderValue(_populationPermissivenessInput, _populationPermissivenessValueLabel, settings.CompatibilityColonyProbabilityMultiplier);
		UpdateCompatibilityOverrideVisibility(settings);
	}

	private void OnCompatibilityPressureChanged(double _value)
	{
		UpdateCompatibilityValueLabels();
		RefreshSummary();
	}

	private static int GenerateHiddenSeed()
	{
		long ticksUsec = unchecked((long)Time.GetTicksUsec());
		long unixTimeUsec = (long)(Time.GetUnixTimeFromSystem() * 1000000.0);
		long combined = (ticksUsec ^ unixTimeUsec) & 0x7FFFFFFF;
		if (combined < 1)
		{
			combined = 1;
		}

		return (int)combined;
	}

	private void ApplyLayoutPolish()
	{
		if (_parameterVBox != null)
		{
			ApplyRowSpacing(_parameterVBox);
		}

		if (_populationPermissivenessRow != null)
		{
			_populationPermissivenessRow.Visible = false;
		}

		SetRowVisible(_temperateWorldBiasRow, false);
		SetRowVisible(_harshWorldBiasRow, false);
		SetRowVisible(_terrestrialWorldBiasRow, false);
		SetRowVisible(_nativeLifeBiasRow, false);
		SetRowVisible(_mainworldPolicyRow, false);

		if (_loadButton != null)
		{
			_loadButton.Visible = false;
		}

		if (_forceLifeOnSupportableWorldsCheck != null)
		{
			_forceLifeOnSupportableWorldsCheck.TooltipText = "Generation override, not a scientific model.\nWhen enabled, supportable worlds keep native life instead of losing it to the later life-roll.\nWorlds that fail the biology support gate still stay lifeless.";
		}

		if (_mainworldPolicyOption != null)
		{
			_mainworldPolicyOption.TooltipText = "This tells Space Opera generation whether it should ignore, prefer, or require a strong mainworld candidate.\nRequire pushes harder for one clearly playable focal world.";
		}

		ApplyCompatibilityTooltip(_temperateWorldBiasInput, _temperateWorldBiasValueLabel, "Higher values fill more good temperate slots with worlds.\nLower values leave more of those slots empty.");
		ApplyCompatibilityTooltip(_harshWorldBiasInput, _harshWorldBiasValueLabel, "Higher values allow more hot, cold, and otherwise harsh worlds to survive slot filling.\nLower values prune harsh slots more aggressively.");
		ApplyCompatibilityTooltip(_terrestrialWorldBiasInput, _terrestrialWorldBiasValueLabel, "Higher values favor rocky and super-Earth mainworld candidates over mini-Neptunes and giants.\nLower values relax that bias.");
		ApplyCompatibilityTooltip(_nativeLifeBiasInput, _nativeLifeBiasValueLabel, "Higher values make supportable worlds more likely to keep native life.\nLower values make life rarer even when a world can support it.");
		ApplyCompatibilityTooltip(_populationPermissivenessInput, _populationPermissivenessValueLabel, "Higher values make colonies and inhabited outposts more common.\nLower values make settled worlds sparser.");
	}

	private void UpdateCompatibilityOverrideVisibility(GenerationUseCaseSettings settings)
	{
		bool showSpaceOperaOverrides = settings.RulesetMode == GenerationUseCaseSettings.RulesetModeType.Traveller;
		SetRowVisible(_mainworldPolicyRow, showSpaceOperaOverrides);
		SetRowVisible(_temperateWorldBiasRow, showSpaceOperaOverrides);
		SetRowVisible(_harshWorldBiasRow, showSpaceOperaOverrides);
		SetRowVisible(_terrestrialWorldBiasRow, showSpaceOperaOverrides);
		SetRowVisible(_nativeLifeBiasRow, showSpaceOperaOverrides);
		SetRowVisible(_populationPermissivenessRow, showSpaceOperaOverrides);
		UpdateCompatibilityValueLabels();
	}

	private void UpdateCompatibilityValueLabels()
	{
		UpdateCompatibilityValueLabel(_temperateWorldBiasInput, _temperateWorldBiasValueLabel);
		UpdateCompatibilityValueLabel(_harshWorldBiasInput, _harshWorldBiasValueLabel);
		UpdateCompatibilityValueLabel(_terrestrialWorldBiasInput, _terrestrialWorldBiasValueLabel);
		UpdateCompatibilityValueLabel(_nativeLifeBiasInput, _nativeLifeBiasValueLabel);
		UpdateCompatibilityValueLabel(_populationPermissivenessInput, _populationPermissivenessValueLabel);
	}

	private static void UpdateCompatibilityValueLabel(Range? slider, Label? label)
	{
		if (slider == null || label == null)
		{
			return;
		}

		label.Text = $"{slider.Value:0.00}x";
	}

	private static void SetCompatibilitySliderValue(Range? slider, Label? label, double value)
	{
		if (slider != null)
		{
			slider.Value = value;
		}

		UpdateCompatibilityValueLabel(slider, label);
	}

	private static void SetRowVisible(Control? row, bool isVisible)
	{
		if (row != null)
		{
			row.Visible = isVisible;
		}
	}

	private static void ApplyCompatibilityTooltip(Control? inputControl, Control? valueLabel, string tooltip)
	{
		if (inputControl != null)
		{
			inputControl.TooltipText = tooltip;
		}

		if (valueLabel != null)
		{
			valueLabel.TooltipText = tooltip;
		}
	}

	private partial void CacheStellarNodeReferences();

	private partial void ConnectStellarSignals();

	private partial void ApplyStellarDefaults();

	private partial void ApplyStellarParameterTooltips();

	private partial void CacheLifeNodeReferences();

	private partial void ConnectLifeSignals();

	private partial void ApplyLifeDefaults();

	private partial void ApplyLifeParameterTooltips();

	private partial void ApplyLifeSettingsFromControls(GenerationUseCaseSettings settings);

	private partial void ApplyTravellerLifeDefaultsToControls();

	private partial void CacheScienceHelpNodeReferences();

	private partial void ConnectScienceHelpSignals();

	private partial void InitializeScienceHelpUi();

	private partial StellarGenerationProfile BuildStellarProfileFromControls();

	private partial string BuildStellarProfileSummary(StellarGenerationProfile profile);

	private static void ApplyRowSpacing(Node root)
	{
		foreach (Node child in root.GetChildren())
		{
			if (child is HBoxContainer row)
			{
				row.AddThemeConstantOverride("separation", 10);
			}

			ApplyRowSpacing(child);
		}
	}

	private string GetAssumptionText(string parameterId)
	{
		foreach (GenerationParameterDefinition definition in GenerationParameterCatalog.GetSystemDefinitions())
		{
			if (definition.Id == parameterId)
			{
				return definition.AssumptionText;
			}
		}

		return string.Empty;
	}

	private static Array<int> ParseSpectralHints(string text)
	{
		Array<int> result = new();
		if (string.IsNullOrWhiteSpace(text))
		{
			return result;
		}

		string[] parts = text.Split(',', System.StringSplitOptions.RemoveEmptyEntries | System.StringSplitOptions.TrimEntries);
		foreach (string rawPart in parts)
		{
			string part = rawPart.ToUpperInvariant();
			if (StarClass.TryParseLetter(part, out StarClass.SpectralClass spectralClass))
			{
				result.Add((int)spectralClass);
			}
		}

		return result;
	}

	private static string FormatSpectralHints(Array<int> hints)
	{
		if (hints.Count == 0)
		{
			return "Any";
		}

		System.Collections.Generic.List<string> parts = new();
		foreach (int hint in hints)
		{
			if (System.Enum.IsDefined(typeof(StarClass.SpectralClass), hint))
			{
				parts.Add(((StarClass.SpectralClass)hint).ToString());
			}
		}

		return string.Join(", ", parts);
	}
}
